export const monthStorage = {
  1: ["한", "Han"],
  2: ["강", "Gang"],
  3: ["이", "Lee"],
  4: ["조", "Jo"],
  5: ["윤", "Yoon"],
  6: ["김", "Kim"],
  7: ["임", "Lim"],
  8: ["장", "Jang"],
  9: ["최", "Choi"],
  10: ["박", "Park"],
  11: ["서", "Seo"],
  12: ["배", "Bae"],
};

export const dayStorage = {
  1: ["진", `Good Nice`, "jin"],
  2: ["화", `Flower`, "hwa"],
  3: ["지", `Wisdom`, "ji"],
  4: ["효", `Filial Love`, "hyo"],
  5: ["시", `Proper`, "si"],
  6: ["도", `Understanding`, "do"],
  7: ["수", "Eminent", "su"],
  8: ["재", "Clever", "jae"],
  9: ["현", "Sensible", "hyun"],
  10: ["소", "Simple and Honest", "so"],
  11: ["은", "Merciful", "eun"],
  12: ["경", "Polite", "gyung"],
  13: ["유", "Gentle", "yu"],
  14: ["명", "Cheerful", "myung"],
  15: ["선", "Kind Friendly", "sun"],
  16: ["예", "Courteous", "yae"],
  17: ["원", "The best", "won"],
  18: ["서", "Silent", "seo"],
  19: ["하", "Leadership", "ha"],
  20: ["주", "King", "ju"],
  21: ["보", "Responsible", "bo"],
  22: ["영", "Intelligent", "young"],
  23: ["슬", "Wise and Sagacious", "seul"],
  24: ["혜", "Broud-minded", "hae"],
  25: ["정", "Affection", "jung"],
  26: ["신", "Trust", "sin"],
  27: ["연", "Veteran", "yeon"],
  28: ["성", "Natural disposition", "sung"],
  29: ["인", "Righteous", "in"],
  30: ["제", "Comfortable", "jae"],
  31: ["동", "Active", "dong"],
};

export const yearFemaleStorage = {
  1: ["라", "hardworking woman", "la"],
  2: ["미", "pretty woman", "mea"],
  3: ["채", "twinkle woman", "chae"],
  4: ["이", "pure woman", "i"],
  5: ["란", "attractive woman", "ran"],
  6: ["민", "shrewd woman", "min"],
  7: ["희", "hopeful woman", "hee"],
  8: ["나", "strong woman", "na"],
  9: ["아", "cute woman", "a"],
  0: ["애", "lovely woman", "ae"],
};

export const yearMaleStorage = {
  1: ["혁", "talented man", "hyeok"],
  2: ["석", "muscular man", "seok"],
  3: ["준", "good man deep down inside", "jun"],
  4: ["빈", "cunning and crafty man", "bin"],
  5: ["우", "service-minded man", "u"],
  6: ["규", "resourceful man", "gyu"],
  7: ["훈", "handsome man", "hoon"],
  8: ["근", "thoughtful man", "geun"],
  9: ["호", "curious passionate man", "ho"],
  0: ["섭", "man who's gonna change the world", "sub"],
};
