export const monthStorage = {
  1: ["한", "Han"],
  2: ["강", "Gang"],
  3: ["이", "Lee"],
  4: ["조", "Jo"],
  5: ["윤", "Yoon"],
  6: ["김", "Kim"],
  7: ["임", "Lim"],
  8: ["장", "Jang"],
  9: ["최", "Choi"],
  10: ["박", "Park"],
  11: ["서", "Seo"],
  12: ["배", "Bae"],
};

export const dayStorage = {
  1: ["진", `Having a lot of curiousity,`, "jin"],
  2: ["화", `With a fiery passion,`, "hwa"],
  3: ["지", `Wise like Athens,`, "ji"],
  4: ["효", `Having a lot of filial piety,`, "hyo"],
  5: ["시", `Having a straight thoughts,`, "si"],
  6: ["도", `Having a deep understanding,`, "do"],
  7: ["수", "As intelligent as a genius,", "su"],
  8: ["재", "As clever as a genius,", "jae"],
  9: ["현", "Very sensitive,", "hyun"],
  10: ["소", "Humble and honest,", "so"],
  11: ["은", "Always being considerate,", "eun"],
  12: ["경", "Being polite to all,", "gyung"],
  13: ["유", "Gentle as a lamb,", "yu"],
  14: ["명", "Efficient and enterprising,", "myung"],
  15: ["선", "Having a lot of affectionation,", "sun"],
  16: ["예", "Being altruistic to all,", "yae"],
  17: ["원", "Ambitious like Genghis Khan,", "won"],
  18: ["서", "Astute and candid,", "seo"],
  19: ["하", "Having a great leadership,", "ha"],
  20: ["주", "Qualify as a king,", "ju"],
  21: ["보", "Careful and calm,", "bo"],
  22: ["영", "Having a lot of confident,", "young"],
  23: ["슬", "Smart and creative,", "seul"],
  24: ["혜", "Courageous as a lion,", "hae"],
  25: ["정", "Communicative and deliberate,", "jung"],
  26: ["신", "Always being diligent,", "sin"],
  27: ["연", "Having a great ability,", "yeon"],
  28: ["성", "Extrovert and enterprising,", "sung"],
  29: ["인", "Generous and good-natured,", "in"],
  30: ["제", "Industrious and hardworking,", "jae"],
  31: ["동", "Gracious as well as intense,", "dong"],
};

export const yearFemaleStorage = {
  1: ["라", "dressed well woman", "la"],
  2: ["미", "pretty woman", "mea"],
  3: ["채", "twinkle woman", "chae"],
  4: ["이", "pure woman", "i"],
  5: ["란", "attractive woman", "ran"],
  6: ["민", "shrewd woman", "min"],
  7: ["희", "gorgeous woman", "hee"],
  8: ["나", "strong woman", "na"],
  9: ["아", "cute woman", "a"],
  0: ["애", "lovely woman", "ae"],
};

export const yearMaleStorage = {
  1: ["혁", "talented man", "hyeok"],
  2: ["석", "muscular man", "seok"],
  3: ["준", "godd looknig man", "jun"],
  4: ["빈", "crafty man", "bin"],
  5: ["우", "gorgeous man", "u"],
  6: ["규", "outstanding man", "gyu"],
  7: ["훈", "handsome man", "hoon"],
  8: ["근", "progressive man", "geun"],
  9: ["호", "passionate man", "ho"],
  0: ["섭", "man who's gonna change the world", "sub"],
};
